### ISSUE TITLE
Make default projects

### ISSUE THREAD

**Issue by buuck** [openecometrics/calculator#7]
Add one or more default projects to the `project` table that all users can see, with `authorId = default`. This will require changing the SQL query to show all projects matching the user's `authorId` as well as `default`.

**Comment by buuck** [comment]
@pgzmnk if I just change `authorId` for a single row, will that screw anything up? Are the `id` and `authorId` columns related to each other?

**Comment by pgzmnk** [comment]
The columns aren't related. Feel free to manually edit and create records in the DB. 

If you prefer, you can also interact with the DB via the DuckDB CLI. Same credentials as you already have.

**Comment by pgzmnk** [comment]
https://duckdb.org/docs/installation/index

`brew install duckdb `
